package seed

import "krankenprep/models"

var TheWarWithinData = models.Expansion{
	Name: "The War Within",
	Slug: "the-war-within",
	Seasons: []models.Season{
		{
			Name:      "Season 1",
			Order:     1,
			IsCurrent: false,
			Raids: []models.Raid{
				{
					Name:         "Nerub-ar Palace",
					Slug:         "nerubar palace",
					SplashImgUrl: "https://wow.zamimg.com/optimized/guide-header-revamp/uploads/guide/header/f9dcd9dd54abd5152d9cd0c00478db9da96e7ac2.jpg",
					Order:        1,
					Bosses: []models.Boss{
						{
							Name:         "Ulgrax",
							Order:        1,
							Slug:         "ulgrax",
							IconImgUrl:   "https://cdn.raiderio.net/images/wow/icons/large/inv_achievement_raidnerubian_nerubianhulk.jpg",
							SplashImgUrl: "https://cdn.raiderio.net/images/wow/icons/large/inv_achievement_raidnerubian_nerubianhulk.jpg",
						},
						{
							Name:         "Bloodbound Horror",
							Order:        2,
							Slug:         "bloodbound-horror",
							IconImgUrl:   "	https://cdn.raiderio.net/images/wow/icons/large/inv_achievement_raidnerubian_blackblood.jpg",
							SplashImgUrl: "	https://cdn.raiderio.net/images/wow/icons/large/inv_achievement_raidnerubian_blackblood.jpg",
						},
						{
							Name:         "Sikran",
							Order:        3,
							Slug:         "sikran",
							IconImgUrl:   "https://cdn.raiderio.net/images/wow/icons/large/inv_achievement_raidnerubian_nerubianevolved.jpg",
							SplashImgUrl: "https://cdn.raiderio.net/images/wow/icons/large/inv_achievement_raidnerubian_nerubianevolved.jpg",
						},
						{
							Name:         "Rasha'nan",
							Order:        4,
							Slug:         "rasha-nan",
							IconImgUrl:   "https://cdn.raiderio.net/images/wow/icons/large/in…chievement_raidnerubian_flyingnerubianevolved.jpg",
							SplashImgUrl: "https://cdn.raiderio.net/images/wow/icons/large/in…chievement_raidnerubian_flyingnerubianevolved.jpg",
						},
						{
							Name:         "Broodtwister Ovi'nax",
							Order:        5,
							Slug:         "broodtwister-ovinax",
							IconImgUrl:   "https://cdn.raiderio.net/images/wow/icons/large/inv_achievement_raidnerubian_swarmmother.jpg",
							SplashImgUrl: "https://cdn.raiderio.net/images/wow/icons/large/inv_achievement_raidnerubian_swarmmother.jpg",
						},
						{
							Name:         "Princess Ky'veza",
							Order:        6,
							Slug:         "princess-kyveza",
							IconImgUrl:   "	https://cdn.raiderio.net/images/wow/icons/large/inv_achievement_raidnerubian_etherealassasin.jpg",
							SplashImgUrl: "	https://cdn.raiderio.net/images/wow/icons/large/inv_achievement_raidnerubian_etherealassasin.jpg",
						},
						{
							Name:         "Silken Court",
							Order:        7,
							Slug:         "silken-court",
							IconImgUrl:   "https://cdn.raiderio.net/images/wow/icons/large/inv_achievement_raidnerubian_etherealassasin.jpg",
							SplashImgUrl: "	https://cdn.raiderio.net/images/wow/icons/large/inv_achievement_raidnerubian_etherealassasin.jpg",
						},
						{
							Name:         "Queen Ansurek",
							Order:        8,
							Slug:         "queen-ansurek",
							IconImgUrl:   "https://cdn.raiderio.net/images/wow/icons/large/inv_achievement_raidnerubian_queenansurek.jpg",
							SplashImgUrl: "https://cdn.raiderio.net/images/nerubar-palace/headers/md/queen-ansurek.jpg",
						},
					},
				},
			},
		},
		{
			Name:      "Season 2",
			Order:     2,
			IsCurrent: false,
			Raids: []models.Raid{{
				Name:         "Liberation of Undermine",
				Slug:         "liberation-of-undermine",
				SplashImgUrl: "https://wow.zamimg.com/optimized/guide-header-revamp/uploads/guide/header/150e48b718bcad17e31dab3af7278f63e72f89af.jpg",
				Order:        2,
				Bosses: []models.Boss{
					{
						Name:         "Vexie and the Geargrinders",
						Order:        1,
						Slug:         "vexie-and-the-geargrinders",
						IconImgUrl:   "https://cdn.raiderio.net/images/wow/icons/large/inv_111_raid_achievement_vexieandthegeargrinders.jpg",
						SplashImgUrl: "https://cdn.raiderio.net/images/liberation-of-undermine/headers/md/vexie-and-the-geargrinders.jpg",
					},
					{
						Name:         "Cauldron of Carnage",
						Order:        2,
						Slug:         "cauldron-of-carnage",
						IconImgUrl:   "https://cdn.raiderio.net/images/wow/icons/large/inv_11_arenaboss_colossalclash.jpg",
						SplashImgUrl: "https://cdn.raiderio.net/images/liberation-of-undermine/headers/md/cauldron-of-carnage.jpg",
					},
					{
						Name:         "Rik Reverb",
						Order:        3,
						Slug:         "rik-reverb",
						IconImgUrl:   "https://cdn.raiderio.net/images/wow/icons/large/inv_111_raid_achievement_rikreverb.jpg",
						SplashImgUrl: "https://cdn.raiderio.net/images/liberation-of-undermine/headers/md/rik-reverb.jpg",
					},
					{
						Name:         "Stix Bunkjunker",
						Order:        4,
						Slug:         "stix-bunkjunker",
						IconImgUrl:   "https://cdn.raiderio.net/images/wow/icons/large/inv_111_raid_achievement_stixbunkjunker.jpg",
						SplashImgUrl: "https://cdn.raiderio.net/images/liberation-of-undermine/headers/md/stix-bunkjunker.jpg",
					},
					{
						Name:         "Sprocketmonger Lockenstock",
						Order:        5,
						Slug:         "sprocketmonger-lockenstock",
						IconImgUrl:   "https://cdn.raiderio.net/images/wow/icons/large/inv_111_raid_achievement_sprocketmongerlocknstock.jpg",
						SplashImgUrl: "https://cdn.raiderio.net/images/liberation-of-undermine/headers/md/sprocketmonger-lockenstock.jpg",
					},
					{
						Name:         "The One-Armed Bandit",
						Order:        6,
						Slug:         "the-one-armed-bandit",
						IconImgUrl:   "https://cdn.raiderio.net/images/wow/icons/large/inv_111_raid_achievement_onearmedbandit.jpg",
						SplashImgUrl: "https://cdn.raiderio.net/images/liberation-of-undermine/headers/md/onearmed-bandit.jpg",
					},
					{
						Name:         "Mug'Zee, Heads of Security",
						Order:        7,
						Slug:         "mugzee",
						IconImgUrl:   "https://cdn.raiderio.net/images/wow/icons/large/inv_111_raid_achievement_mugzeeheadsofsecurity.jpg",
						SplashImgUrl: "	https://cdn.raiderio.net/images/liberation-of-undermine/headers/md/mugzee-heads-of-security.jpg",
					},
					{
						Name:         "Chrome King Gallywix",
						Order:        8,
						Slug:         "chrome-king-gallywix",
						IconImgUrl:   "https://cdn.raiderio.net/images/wow/icons/large/inv_111_raid_achievement_chromekinggallywix.jpg",
						SplashImgUrl: "	https://cdn.raiderio.net/images/liberation-of-undermine/headers/md/chrome-king-gallywix.jpg",
					},
				},
			}},
		},
		{
			Name:      "Season 3",
			Order:     3,
			IsCurrent: true,
			Raids: []models.Raid{
				{
					Name:         "Manaforge Omega",
					Slug:         "manaforge-omega",
					SplashImgUrl: "https://wow.zamimg.com/optimized/guide-header-revamp/images/content/tall-headers/retail/categories/raids-manaforge-omega.jpg",
					Order:        3,
					Bosses: []models.Boss{
						{
							Name:         "Plexus Sentinel",
							Order:        1,
							Slug:         "plexus-sentinel",
							IconImgUrl:   "https://cdn.raiderio.net/images/wow/icons/large/inv_112_achievement_raid_automaton.jpg",
							SplashImgUrl: "https://cdn.raiderio.net/images/manaforge-omega/headers/md/plexus-sentinel.jpg",
						},
						{
							Name:         "Soulbinder Naazindhri",
							Order:        2,
							Slug:         "soulbinder-naazindhri",
							IconImgUrl:   "https://cdn.raiderio.net/images/wow/icons/large/inv_112_achievement_raid_binder.jpg",
							SplashImgUrl: "https://cdn.raiderio.net/images/manaforge-omega/headers/md/soulbinder-naazindhri.jpg",
						},
						{
							Name:         "Loomi'thar",
							Order:        3,
							Slug:         "loomithar",
							IconImgUrl:   "https://cdn.raiderio.net/images/wow/icons/large/inv_112_achievement_raid_silkworm.jpg",
							SplashImgUrl: "https://cdn.raiderio.net/images/manaforge-omega/headers/md/loomithar.jpg",
						},
						{
							Name:         "Forgeweaver Araz",
							Order:        4,
							Slug:         "forgeweaver-araz",
							IconImgUrl:   "https://cdn.raiderio.net/images/wow/icons/large/inv_112_achievement_raid_engineer.jpg",
							SplashImgUrl: "https://cdn.raiderio.net/images/manaforge-omega/headers/md/forgeweaver-araz.jpg",
						},
						{
							Name:         "The Soul Hunters",
							Order:        5,
							Slug:         "the-soul-hunters",
							IconImgUrl:   "https://cdn.raiderio.net/images/wow/icons/large/inv_112_achievement_raid_dhcouncil.jpg",
							SplashImgUrl: "https://cdn.raiderio.net/images/manaforge-omega/headers/md/the-soul-hunters.jpg",
						},
						{
							Name:         "Fractilus",
							Order:        6,
							Slug:         "fractilus",
							IconImgUrl:   "https://cdn.raiderio.net/images/wow/icons/large/inv_112_achievement_raid_glasselemental.jpg",
							SplashImgUrl: "https://cdn.raiderio.net/images/manaforge-omega/headers/md/fractillus.jpg",
						},
						{
							Name:         "Nexus-King Salhaadar",
							Order:        7,
							Slug:         "nexus-king-salhaadar",
							IconImgUrl:   "https://cdn.raiderio.net/images/wow/icons/large/inv_112_achievement_raid_salhadaar.jpg",
							SplashImgUrl: "https://cdn.raiderio.net/images/manaforge-omega/headers/md/nexus-king-salhadaar.jpg",
						},
						{
							Name:         "Dimensius, the All Devouring",
							Order:        8,
							Slug:         "dimensius",
							IconImgUrl:   "https://cdn.raiderio.net/images/wow/icons/large/inv_112_achievement_raid_dimensius.jpg",
							SplashImgUrl: "https://cdn.raiderio.net/images/manaforge-omega/headers/md/dimensius.jpg",
						},
					},
				},
			},
		},
	},
}
