package seed

import "krankenprep/models"

var EuServers = []models.Server{
	{Name: "Blackrock", Region: "eu", Language: "de"},
	{Name: "Draenor", Region: "eu", Language: "en"},
	{Name: "Hyjal", Region: "eu", Language: "fr"},
	{Name: "Kazzak", Region: "eu", Language: "en"},
	{Name: "Ragnaros", Region: "eu", Language: "en"},
	{Name: "Silvermoon", Region: "eu", Language: "en"},
	{Name: "Twisting Nether", Region: "eu", Language: "en"},
	{Name: "Ревущий фьорд", Region: "eu", Language: "ru"},
	{Name: "Connected Blackmoore", Region: "eu", Language: "de"},
	{Name: "Connected Mal'Ganis", Region: "eu", Language: "de"},
	{Name: "Connected Sanguino", Region: "eu", Language: "es"},
	{Name: "Connected Al'Akir", Region: "eu", Language: "en"},
	{Name: "Connected Tarren Mill", Region: "eu", Language: "en"},
	{Name: "Connected Drak'thul", Region: "eu", Language: "en"},
	{Name: "Eredar", Region: "eu", Language: "de"},
	{Name: "Connected Kargath", Region: "eu", Language: "de"},
	{Name: "Ravencrest", Region: "eu", Language: "en"},
	{Name: "Ysondre", Region: "eu", Language: "fr"},
	{Name: "Connected Stormreaver", Region: "eu", Language: "en"},
	{Name: "Stormscale", Region: "eu", Language: "en"},
	{Name: "Antonidas", Region: "eu", Language: "de"},
	{Name: "Archimonde", Region: "eu", Language: "fr"},
	{Name: "Nemesis", Region: "eu", Language: "it"},
	{Name: "Гордунни", Region: "eu", Language: "ru"},
	{Name: "Connected Dalaran", Region: "eu", Language: "fr"},
	{Name: "Connected Sylvanas", Region: "eu", Language: "en"},
	{Name: "Connected Confrérie du Thorium", Region: "eu", Language: "fr"},
	{Name: "Свежеватель Душ", Region: "eu", Language: "ru"},
	{Name: "Connected Elune", Region: "eu", Language: "fr"},
	{Name: "Argent Dawn", Region: "eu", Language: "en"},
	{Name: "Connected Shattered Hand", Region: "eu", Language: "en"},
	{Name: "Connected Doomhammer", Region: "eu", Language: "en"},
	{Name: "Connected Grim Batol", Region: "eu", Language: "en"},
	{Name: "Connected Kilrogg", Region: "eu", Language: "en"},
	{Name: "Connected Defias Brotherhood", Region: "eu", Language: "en"},
	{Name: "Connected Uldaman", Region: "eu", Language: "fr"},
	{Name: "Magtheridon", Region: "eu", Language: "en"},
	{Name: "Connected Azjol-Nerub", Region: "eu", Language: "en"},
	{Name: "Connected Kael'Thas", Region: "eu", Language: "fr"},
	{Name: "Connected Stormrage", Region: "eu", Language: "en"},
	{Name: "Connected Emerald Dream", Region: "eu", Language: "en"},
	{Name: "Connected Anub'arak", Region: "eu", Language: "de"},
	{Name: "Connected Sargeras", Region: "eu", Language: "fr"},
	{Name: "Frostwolf", Region: "eu", Language: "de"},
	{Name: "Connected Aggramar", Region: "eu", Language: "en"},
	{Name: "Well of Eternity", Region: "eu", Language: "it"},
	{Name: "Outland", Region: "eu", Language: "en"},
	{Name: "Connected Sunstrider", Region: "eu", Language: "en"},
	{Name: "Connected Dun Morogh", Region: "eu", Language: "de"},
	{Name: "Connected Zirkel des Cenarius", Region: "eu", Language: "de"},
	{Name: "Connected Пиратская Бухта", Region: "eu", Language: "ru"},
	{Name: "Connected Lothar", Region: "eu", Language: "de"},
	{Name: "Connected Nordrassil", Region: "eu", Language: "en"},
	{Name: "Aegwynn", Region: "eu", Language: "de"},
	{Name: "Connected Anetheron", Region: "eu", Language: "de"},
	{Name: "Connected The Maelstrom", Region: "eu", Language: "en"},
	{Name: "Connected Dun Modr", Region: "eu", Language: "es"},
	{Name: "Connected Arthas", Region: "eu", Language: "de"},
	{Name: "Connected Alleria", Region: "eu", Language: "de"},
	{Name: "Connected Malfurion", Region: "eu", Language: "de"},
	{Name: "Khaz Modan", Region: "eu", Language: "fr"},
	{Name: "Connected Garrosh", Region: "eu", Language: "de"},
	{Name: "Connected Eonar", Region: "eu", Language: "en"},
	{Name: "Connected Chants éternels", Region: "eu", Language: "fr"},
	{Name: "Connected Alexstrasza", Region: "eu", Language: "de"},
	{Name: "Connected Shadowsong", Region: "eu", Language: "en"},
	{Name: "Connected Kult der Verdammten", Region: "eu", Language: "de"},
	{Name: "Connected Frostwhisper", Region: "eu", Language: "en"},
	{Name: "Connected Alonsus", Region: "eu", Language: "en"},
	{Name: "Connected Destromath", Region: "eu", Language: "de"},
	{Name: "Connected Thunderhorn", Region: "eu", Language: "en"},
	{Name: "Connected Twilight's Hammer", Region: "eu", Language: "en"},
	{Name: "Connected Ysera", Region: "eu", Language: "de"},
	{Name: "Connected Moonglade", Region: "eu", Language: "en"},
	{Name: "Connected Medivh", Region: "eu", Language: "fr"},
	{Name: "Connected Король-лич", Region: "eu", Language: "ru"},
	{Name: "Азурегос", Region: "eu", Language: "ru"},
	{Name: "Ясеневый лес", Region: "eu", Language: "ru"},
	{Name: "Connected Разувий", Region: "eu", Language: "ru"},
	{Name: "Вечная Песня", Region: "eu", Language: "ru"},
	{Name: "Connected Illidan", Region: "eu", Language: "fr"},
	{Name: "Die Aldor", Region: "eu", Language: "de"},
	{Name: "Connected Tyrande", Region: "eu", Language: "es"},
	{Name: "Connected Exodar", Region: "eu", Language: "es"},
	{Name: "Дракономор", Region: "eu", Language: "ru"},
	{Name: "Connected Khaz'goroth", Region: "eu", Language: "de"},
	{Name: "Chamber of Aspects", Region: "eu", Language: "en"},
	{Name: "Connected Onyxia", Region: "eu", Language: "de"},
	{Name: "Connected Area 52", Region: "eu", Language: "de"},
	{Name: "Connected Lightbringer", Region: "eu", Language: "en"},
	{Name: "Connected Bloodhoof", Region: "eu", Language: "en"},
	{Name: "Страж смерти", Region: "eu", Language: "ru"},

	// n/a entries (still valid)
	{Name: "Molten Core", Region: "eu", Language: "en"},
	{Name: "Shadowmoon", Region: "eu", Language: "en"},
	{Name: "Stonemaul", Region: "eu", Language: "en"},
	{Name: "Warsong", Region: "eu", Language: "en"},
}

var NaServers = []models.Server{
	{Name: "Area 52", Region: "na", Language: "en"},
	{Name: "Illidan", Region: "na", Language: "en"},
	{Name: "Mal'Ganis", Region: "na", Language: "en"},
	{Name: "Sargeras", Region: "na", Language: "en"},
	{Name: "Stormrage", Region: "na", Language: "en"},
	{Name: "Tichondrius", Region: "na", Language: "en"},
	{Name: "Zul'jin", Region: "na", Language: "en"},
	{Name: "Connected Jubei'Thos", Region: "na", Language: "en (oc)"},
	{Name: "Thrall", Region: "na", Language: "en"},
	{Name: "Ragnaros", Region: "na", Language: "es"},
	{Name: "Azralon", Region: "na", Language: "pt (br)"},
	{Name: "Bleeding Hollow", Region: "na", Language: "en"},
	{Name: "Proudmoore", Region: "na", Language: "en"},
	{Name: "Emerald Dream", Region: "na", Language: "en"},
	{Name: "Hyjal", Region: "na", Language: "en"},
	{Name: "Barthilas", Region: "na", Language: "en (oc)"},
	{Name: "Dalaran", Region: "na", Language: "en"},
	{Name: "Connected Burning Blade", Region: "na", Language: "en"},
	{Name: "Kil'Jaeden", Region: "na", Language: "en"},
	{Name: "Moon Guard", Region: "na", Language: "en"},
	{Name: "Quel'Thalas", Region: "na", Language: "es"},
	{Name: "Connected Khaz'goroth", Region: "na", Language: "en (oc)"},
	{Name: "Connected Whisperwind", Region: "na", Language: "en"},
	{Name: "Kel'Thuzad", Region: "na", Language: "en"},
	{Name: "Connected Trollbane", Region: "na", Language: "en"},
	{Name: "Connected Spirestone", Region: "na", Language: "en"},
	{Name: "Connected Sen'Jin", Region: "na", Language: "en"},
	{Name: "Connected Silvermoon", Region: "na", Language: "en"},
	{Name: "Connected Mug'thol", Region: "na", Language: "en"},
	{Name: "Stormreaver", Region: "na", Language: "en"},
	{Name: "Connected Deathwing", Region: "na", Language: "en"},
	{Name: "Connected Shadowmoon", Region: "na", Language: "en"},
	{Name: "Connected Shattered Hand", Region: "na", Language: "en"},
	{Name: "Connected Burning Legion", Region: "na", Language: "en"},
	{Name: "Connected Zuluhed", Region: "na", Language: "en"},
	{Name: "Connected Thunderlord", Region: "na", Language: "en"},
	{Name: "Connected Ner'zhul", Region: "na", Language: "en"},
	{Name: "Connected Bonechewer", Region: "na", Language: "en"},
	{Name: "Wyrmrest Accord", Region: "na", Language: "en"},
	{Name: "Connected Nagrand", Region: "na", Language: "en (oc)"},
	{Name: "Connected Alleria", Region: "na", Language: "en"},
	{Name: "Connected Khaz Modan", Region: "na", Language: "en"},
	{Name: "Connected Crushridge", Region: "na", Language: "en"},
	{Name: "Connected Cho'gall", Region: "na", Language: "en"},
	{Name: "Connected Alterac Mountains", Region: "na", Language: "en"},
	{Name: "Connected Eredar", Region: "na", Language: "en"},
	{Name: "Connected Aggramar", Region: "na", Language: "en"},
	{Name: "Connected Magtheridon", Region: "na", Language: "en"},
	{Name: "Aerie Peak", Region: "na", Language: "en"},
	{Name: "Earthen Ring", Region: "na", Language: "en"},
	{Name: "Connected Suramar", Region: "na", Language: "en"},
	{Name: "Connected Shadow Council", Region: "na", Language: "en"},
	{Name: "Lightbringer", Region: "na", Language: "en"},
	{Name: "Connected Azuremyst", Region: "na", Language: "en"},
	{Name: "Arthas", Region: "na", Language: "en"},
	{Name: "Drakkari", Region: "na", Language: "es"},
	{Name: "Turalyon", Region: "na", Language: "en"},
	{Name: "Connected Vek'nilash", Region: "na", Language: "en"},
	{Name: "Connected Silver Hand", Region: "na", Language: "en"},
	{Name: "Connected Maelstrom", Region: "na", Language: "en"},
	{Name: "Connected Nemesis", Region: "na", Language: "pt (br)"},
	{Name: "Connected Bladefist", Region: "na", Language: "en"},
	{Name: "Connected Llane", Region: "na", Language: "en"},
	{Name: "Connected Ravencrest", Region: "na", Language: "en"},
	{Name: "Connected Kilrogg", Region: "na", Language: "en"},
	{Name: "Connected Feathermoon", Region: "na", Language: "en"},
	{Name: "Connected Alexstrasza", Region: "na", Language: "en"},
	{Name: "Connected Dragonblight", Region: "na", Language: "en"},
	{Name: "Connected Kirin Tor", Region: "na", Language: "en"},
	{Name: "Connected Draenor", Region: "na", Language: "en"},
	{Name: "Connected Greymane", Region: "na", Language: "en"},
	{Name: "Connected Shandris", Region: "na", Language: "en"},
	{Name: "Connected Ysera", Region: "na", Language: "en"},
	{Name: "Connected Uther", Region: "na", Language: "en"},
	{Name: "Connected Bloodhoof", Region: "na", Language: "en"},
	{Name: "Connected Argent Dawn", Region: "na", Language: "en"},
	{Name: "Connected Blackhand", Region: "na", Language: "en"},
	{Name: "Connected Doomhammer", Region: "na", Language: "en"},
	{Name: "Connected Shu'halo", Region: "na", Language: "en"},
	{Name: "Connected Rexxar", Region: "na", Language: "en"},
	{Name: "Goldrinn", Region: "na", Language: "pt (br)"},
	{Name: "Darkspear", Region: "na", Language: "en"},
	{Name: "Gallywix", Region: "na", Language: "pt (br)"},
}
